<environment>:
  secret_key_base:
  website_url:
  encrypted_path:
  shopify_api_key:
  shopify_secret:
  yotpo_app_key:
  yotpo_api_url:
  loyalty_lion_api_url:
  loyalty_lion_api_token:
  loyalty_lion_api_secret:
  whitelisted_domains: [] #yaml array
  zendesk_url:
  zendesk_email:
  zendesk_token:
  zendesk_custom_field_ids:
    category:
    brand:
    purpose:
  oms_api_url:
  oms_api_key:
  asdfasdfsa: