name: Check dependencies

on:
  schedule:
    - cron: '30 9 * * 2'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.3.x

    - id: check_outdated
      name: Check outdated bundler dependencies
      run: |
        gem install bundler
        bundle outdated --only-explicit --filter-major | grep '*' > bundle-outdated.txt
        echo
        echo 'Outdated dependencies:'
        cat bundle-outdated.txt
        echo ::set-output name=outdated_count::$(cat bundle-outdated.txt | wc -l)

    - name: Audit bundler dependencies
      run: |
        gem install bundler bundler-audit
        bundle audit

    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C1CSH12H0\",\"text\":\"<!subteam^SG1G5A7U3|@web-developers> the latest audit of <https://github.com/${{ github.repository }}|${{ github.repository }}> dependencies just finished with status: *${{ job.status }}*. Also, ${{ steps.check_outdated.outputs.outdated_count }} dependencies want a major version upgrade.\"}'
      if: always()
